name: NMUI SaaS Deployment

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout to staging"
        uses: actions/checkout@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set release tag
        run: |
            TAG="$(git rev-parse --short HEAD)"
            echo "TAG=${TAG}" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile.standalone
          platforms: linux/amd64
          push: true
          tags: aceix/netmaker-ui-saas:${{ env.TAG }}

      - name: Set up kubectl
        uses: matootie/dokube@v1.4.0
        with:
          personalAccessToken: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          clusterName: main-cluster

      - name: Set k8s deployment image
        run: kubectl set image deployment netmaker-ui netmaker-ui=aceix/netmaker-ui-saas:${{ env.TAG }}

      - name: Deploy to k8s cluster
        run: kubectl rollout restart deploy netmaker-ui

      - name: Verify deployment
        run: kubectl rollout status deployment/netmaker-ui
