name: NMUI SaaS Deployment

on:
  push:
    branches:
      - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout to staging"
        uses: actions/checkout@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile.standalone
          platforms: linux/amd64
          push: true
          tags: aceix/netmaker-ui-saas:${{github.sha | head -c7}}

      - name: Set up kubectl
        uses: matootie/dokube@v1.4.0
        with:
          personalAccessToken: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
          clusterName: main-cluster

      # - name: Install doctl
      #   uses: digitalocean/action-doctl@v2
      #   with:
      #     token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      # - name: Prepare DO KUBECONFIG for staging
      #   run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 main-cluster

      - name: Set k8s deployment image
        run: kubectl set image deployment netmaker-ui netmaker-ui=aceix/netmaker-ui-saas:${{github.sha | head -c7}}

      - name: Deploy to k8s cluster
        run: kubectl rollout restart deploy netmaker-ui

      # - name: Deploy to DigitalOcean Kubernetes
      #   uses: WyriHaximus/github-action-helm3@v3
      #   with:
      #     kubeconfig: $(cat ~/.kube/config)
      #     exec: |
      #       helm upgrade -i netmaker-ui deploy/helm/netmaker-ui/ \
      #       --namespace accounts \
      #       --create-namespace \
      #       --set env=staging \
      #       --set image.pullPolicy=Always \
      #       --set image.tag=$(echo $GITHUB_SHA | head -c7)

      - name: Verify deployment
        run: kubectl rollout status deployment/netmaker-ui
